USE [master]
GO

/****** Object:  Database [SteamStore]    Script Date: 25.11.2019 20:57:35 ******/
CREATE DATABASE [SteamStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SteamStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SteamStore.mdf' , SIZE = 12288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SteamStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SteamStore_log.ldf' , SIZE = 7616KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SteamStore] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SteamStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SteamStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SteamStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SteamStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SteamStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SteamStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [SteamStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SteamStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SteamStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SteamStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SteamStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SteamStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SteamStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SteamStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SteamStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SteamStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SteamStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SteamStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SteamStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SteamStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SteamStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SteamStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SteamStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SteamStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SteamStore] SET  MULTI_USER 
GO

ALTER DATABASE [SteamStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SteamStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SteamStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SteamStore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SteamStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SteamStore] SET  READ_WRITE 
GO

